name: web_charity
description: Web Project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  analog_clock : ^0.1.0 
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^19.4.53
  syncfusion_flutter_charts : ^19.4.53
  http: ^0.13.1
  carousel_slider: ^4.0.0
  responsive_framework: ^0.1.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  